### ISSUE TITLE
selftest for Android Appium 

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-selftest#4]
Hi,

Selftest for Android Appium is required due to [Android support and Appium integration](https://github.com/test-fullautomation/RobotFramework_AIO/issues/96)
- Test app: **TMLSelftest**
- Device under test: **Emulator** or Android phone.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
I put this for the 0.11.0 milestone, too?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I intent to assign this ticket to Tri and I will support him.
Is it fine for you?

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi  @ngoan1608 ,
O.K. for me.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
this is already part of 0.11.0, correct?

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

Test cases are completed by Tri and they can be tested on local machine currently.
I have created https://github.com/test-fullautomation/RobotFramework_AIO/issues/273 to add it to our build pipeline for Github first.
Then the next step is BIOS build pipeline.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 , @huavanthong ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 , @huavanthong ,
what is the status of this issue?
Thank you,
Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

Robot test cases for verifying Appium are done by @trimai3001 .
This ticket can be closed.

Regarding to Appium's test cases execution in our build pipeline, I have created the appropriate ticket in AIO repo as following link to integrate them into our build pipeline.
https://github.com/test-fullautomation/RobotFramework_AIO/issues/273
Tri is testing it and will create PR soon for that issue.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
